{ class_EtsGod, [], a }.

{ class_ResultWriter, ["/simulation_output/output.csv"], a }.

{ class_CityGraph, ["/simulation_input/validation/nodes.xml", "/simulation_input/validation/links.xml"], a }.

{ class_Car, [#{id => "1", origin => "1", destination => "2", start_time => 3, start_link => "1", uuid => "a1c1e61e-12f4-45c4-a770-d7084bdd798a" }], a }.
{ class_Car, [#{id => "2", origin => "1", destination => "3", start_time => 3, start_link => "1", uuid => "76054cc3-3f34-4ff0-b517-daa24fa1f0fb" }], a }.
{ class_Car, [#{id => "3", origin => "1", destination => "4", start_time => 3, start_link => "1", uuid => "a2c06cea-9da9-4218-936b-72bf85bb408e" }], a }.
{ class_Car, [#{id => "4", origin => "1", destination => "5", start_time => 3, start_link => "1", uuid => "e618c03c-047f-4863-8455-31acffde9729" }], a }.
{ class_Car, [#{id => "5", origin => "1", destination => "6", start_time => 3, start_link => "1", uuid => "376955c4-1549-41ce-8951-355ccf2fe0ba" }], a }.
{ class_Car, [#{id => "6", origin => "1", destination => "7", start_time => 3, start_link => "1", uuid => "615a573d-0b52-4462-8d4a-3e033db5dc95" }], a }.
{ class_Car, [#{id => "7", origin => "1", destination => "8", start_time => 3, start_link => "1", uuid => "e51753ac-4bfb-4eb4-92c7-9fe141a40f1b" }], a }.
{ class_Car, [#{id => "8", origin => "1", destination => "2", start_time => 4, start_link => "1", uuid => "be692e39-a505-4c66-908c-70d7b1c1c871" }], a }.
{ class_Car, [#{id => "9", origin => "1", destination => "3", start_time => 4, start_link => "1", uuid => "db198844-a8f7-42a8-bec5-87042063a34e" }], a }.
{ class_Car, [#{id => "10", origin => "1", destination => "4", start_time => 4, start_link => "1", uuid => "e2ad501f-5a10-4d9e-860f-6b457bab154b" }], a }.
{ class_Car, [#{id => "11", origin => "1", destination => "5", start_time => 4, start_link => "1", uuid => "ab1b2fbc-b99b-47f7-92df-7663e97e7a0b" }], a }.
{ class_Car, [#{id => "12", origin => "1", destination => "6", start_time => 4, start_link => "1", uuid => "962f6667-ff0e-453a-b10c-c5231968b632" }], a }.
{ class_Car, [#{id => "13", origin => "1", destination => "7", start_time => 4, start_link => "1", uuid => "9d2dff70-3130-42cd-98da-a0e29b229e7c" }], a }.
{ class_Car, [#{id => "14", origin => "1", destination => "8", start_time => 4, start_link => "1", uuid => "9042e68b-4cb8-433e-8fe3-0f3c8a9f7b92" }], a }.
{ class_Car, [#{id => "15", origin => "1", destination => "2", start_time => 5, start_link => "1", uuid => "bdd3078d-be08-4741-ba36-81b719bf0ad4" }], a }.
{ class_Car, [#{id => "16", origin => "1", destination => "3", start_time => 5, start_link => "1", uuid => "bde0ea28-6220-4b9e-ae99-775f764813a6" }], a }.
{ class_Car, [#{id => "17", origin => "1", destination => "4", start_time => 5, start_link => "1", uuid => "f536e4bd-341d-4509-9d95-4f0930041830" }], a }.
{ class_Car, [#{id => "18", origin => "1", destination => "5", start_time => 5, start_link => "1", uuid => "4237ec53-cf58-4920-999b-e1a1d75646b2" }], a }.
{ class_Car, [#{id => "19", origin => "1", destination => "6", start_time => 5, start_link => "1", uuid => "e6dd45dc-e573-4d0d-bf5d-596b1946a8e1" }], a }.
{ class_Car, [#{id => "20", origin => "1", destination => "7", start_time => 5, start_link => "1", uuid => "96c88098-c73b-4981-af66-33f8cc4facad" }], a }.
{ class_Car, [#{id => "21", origin => "1", destination => "8", start_time => 5, start_link => "1", uuid => "8e9ea251-46c0-4935-984f-1b2143cef30f" }], a }.
{ class_Car, [#{id => "22", origin => "1", destination => "2", start_time => 6, start_link => "1", uuid => "75018e1c-a678-4df4-a147-f33e1cf77991" }], a }.
{ class_Car, [#{id => "23", origin => "1", destination => "3", start_time => 6, start_link => "1", uuid => "d831686d-a509-4478-b987-31933652efa0" }], a }.
{ class_Car, [#{id => "24", origin => "1", destination => "4", start_time => 6, start_link => "1", uuid => "565a90ec-40d6-4a29-92ba-07015bca5b4c" }], a }.
{ class_Car, [#{id => "25", origin => "1", destination => "5", start_time => 6, start_link => "1", uuid => "46b58d14-d7c8-468f-ae75-ff7f037d7401" }], a }.
{ class_Car, [#{id => "26", origin => "1", destination => "6", start_time => 6, start_link => "1", uuid => "330672a6-7619-4f1e-97a2-96eab4661b23" }], a }.
{ class_Car, [#{id => "27", origin => "1", destination => "7", start_time => 6, start_link => "1", uuid => "dfa41aaf-c5a2-4942-83fd-b67e2b386fcb" }], a }.
{ class_Car, [#{id => "28", origin => "1", destination => "8", start_time => 6, start_link => "1", uuid => "f00038ce-0258-4022-b690-d0a64ae27fd7" }], a }.
